# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93154f85a813d9883cf7b1f67151dcd2d143bb0f893456677c31310b661ad7ab5de78cfd5ce1cde78cf7da5f6f4362f411cec62ad2949e33f208fd60a70e2ca7

test:
  secret_key_base: 39cc19d180a6d1f0d5b0b541327a7023a17265d1bfa8d2d0e6cfd741385ca349d09a2c069c87440cf3845cc6d0bf8dc2fe88dd1849e492b6cde33b24c101b1d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
